// #211 t2 — Feature Map: visual, lensed, drill-anywhere product map.
// Data: docs/INDEX.json ONLY (generated by scripts/generate_index.py — zero
// hand-curated map data, dc1). Design ratified S130: LENSES over a stable
// nested-container geometry (product > epic containers > feature tiles);
// work-in-flight items PIN on their HOME node (D156); touches[] cross-highlight.
window.FeatureMapView = (() => {

  const state = { idx: null, productId: null, lens: 'build', sel: null, wtFilter: null };

  function escHtml(s) {
    return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  const WT_CLS = {
    'defect': 'fm-wt-defect', 'external-dependency': 'fm-wt-extdep',
    'enhancement': 'fm-wt-enh', 'operational': 'fm-wt-ops',
    'governance': 'fm-wt-gov', 'feature': 'fm-wt-feat',
  };
  const CODE_CLS = { BUILT: 'fm-built', COVERED: 'fm-built', PARTIAL: 'fm-partial', MISSING: 'fm-missing', NONE: 'fm-missing' };

  function openCards() {
    const done = new Set(['done', 'Done', 'closed', 'abandoned']);
    return state.idx.cards.filter(c => c.pps_id === state.productId && !done.has(c.status));
  }
  function shortTitle(t) {
    // strip a "<product> — " title prefix generically (no product literals — #211 dc1)
    return String(t || '').replace(new RegExp('^' + (state.productId || '') + '\\s*—\\s*', 'i'), '').replace(/\s*\(NFR\)\s*$/, '');
  }

  function pinsFor(nodeId) {
    let pins = openCards().filter(c => (c.feature || c.epic) === nodeId);
    if (state.wtFilter) pins = pins.filter(c => (c.work_type || 'feature') === state.wtFilter);
    return pins;
  }

  // work_type composition of open work homed under an epic (incl. its features) —
  // rendered as a micro-bar on the epic header in EVERY lens (V: the nuance
  // should never hide behind one lens).
  function workMix(epicId) {
    const featIds = state.idx.features.filter(f => f.pps_id === state.productId && f.epic === epicId).map(f => f.id);
    const homes = new Set([epicId, ...featIds]);
    const mix = {};
    openCards().forEach(c => {
      const home = c.feature || c.epic;
      if (homes.has(home)) {
        const wt = c.work_type || 'feature';
        mix[wt] = (mix[wt] || 0) + 1;
      }
    });
    return mix;
  }

  function renderMix(epicId) {
    const mix = workMix(epicId);
    const total = Object.values(mix).reduce((a, b) => a + b, 0);
    if (!total) return '';
    const seg = Object.entries(mix).map(([wt, n]) =>
      `<i class="${WT_CLS[wt] || 'fm-wt-feat'}" style="flex:${n}" title="${n} ${wt}"></i>`).join('');
    return `<span class="fm-mix" title="open work mix">${seg}</span>`;
  }

  function renderStrip() {
    const mix = {};
    openCards().forEach(c => { const wt = c.work_type || 'feature'; mix[wt] = (mix[wt] || 0) + 1; });
    const entries = Object.entries(mix).sort((a, b) => b[1] - a[1]);
    if (!entries.length) return '';
    return `<div class="fm-strip">${entries.map(([wt, n]) =>
      `<button class="fm-strip-chip ${WT_CLS[wt] || 'fm-wt-feat'} ${state.wtFilter === wt ? 'active' : ''}" data-wt="${escHtml(wt)}"
         title="${state.wtFilter === wt ? 'clear filter' : 'filter pins to ' + wt}">${n} ${escHtml(wt)}</button>`).join('')}
      ${state.wtFilter ? `<button class="fm-strip-clear" data-wt="">× clear</button>` : ''}</div>`;
  }

  function renderPins(nodeId) {
    const pins = pinsFor(nodeId);
    if (!pins.length || state.lens !== 'flight') return '';
    return `<span class="fm-pins">${pins.map(c =>
      `<span class="fm-pin ${WT_CLS[c.work_type] || 'fm-wt-feat'}" data-card="${escHtml(c.id)}"
        data-touches="${escHtml((c.touches || []).join(','))}"
        title="#${escHtml(c.id)} ${escHtml(c.title || '')} [${escHtml(c.work_type || 'card')}${c.todos_blocked ? ' · ' + c.todos_blocked + ' blocked' : ''}]">#${escHtml(c.id)}</span>`
    ).join('')}</span>`;
  }

  // #211 phase-0 item 1 — epistemic render: build-lens colours derive from
  // hand-set code_status (no probe yet), so tiles carry the fm-hatched overlay
  // + blame-stamp age in the title. Phase 3 probes flip HealthCore.SENSED and
  // the hatch disappears with zero changes here.
  function epiTitle(node, field) {
    const ep = window.HealthCore.epistemic(node, field);
    return ep.state === 'unverified' ? ` · unverified since ${ep.since || '?'}` : '';
  }
  // #211 phase-1 — five-segment readiness cells (CP grammar: spec·code·test·doc·live).
  // Honest v1 from real data: spec = provenance-aware (the first client's spec is
  // derived-unratified — one measurement shown twice, so NEVER plain green);
  // code/test = hand-set feature statuses (hatched); doc = epic-level manual
  // status inherited (hatched); live = no per-feature signal exists → no-source.
  function manifestFor(pid) {
    return ((state.idx.source_manifests || []).find(m => m.pps_id === pid) || {}).sources || null;
  }
  function rCells(f, epic) {
    const HC = window.HealthCore;
    const cells = [];
    const prov = f.spec_provenance || (epic || {}).spec_provenance;
    cells.push({ k: 'spec', color: prov === 'ratified' ? 'var(--success)' : 'var(--warning)',
      hatch: false, title: `spec: present · provenance: ${prov || 'unknown'}${prov === 'derived-unratified' ? ' — reverse-engineered from code; spec=done+code=done is ONE measurement shown twice' : ''}` });
    [['code', 'code_status', f], ['test', 'testing_status', f]].forEach(([k, fld, node]) => {
      const ep = HC.epistemic(node, fld);
      cells.push(ep.value == null
        ? { k, color: 'transparent', na: true, title: `${k}: no value` }
        : { k, color: HC.color(ep.value), hatch: ep.state === 'unverified', title: `${k}: ${ep.value}${ep.since ? ' · unverified since ' + ep.since : ''}` });
    });
    const epd = HC.epistemic(epic || {}, 'usermanual_status');
    cells.push(epd.value == null
      ? { k: 'doc', color: 'transparent', na: true, title: 'doc: no value' }
      : { k: 'doc', color: HC.color(epd.value), hatch: true, title: `doc: ${epd.value} (epic-level) · unverified since ${epd.since || '?'}` });
    const man = manifestFor(state.productId);
    const live = man && man.live && man.live.reachable;
    cells.push({ k: 'live', color: 'transparent', na: true,
      title: `live: no per-feature deployment signal${live ? ' · product prod IS reachable (manifest probe)' : ''}` });
    return `<span class="fm-rcells">${cells.map(c =>
      `<i class="fm-rc${c.na ? ' fm-rc-na' : ''}${c.hatch ? ' fm-hatched' : ''}" style="background:${c.color}" title="${escHtml(c.title)}"></i>`).join('')}</span>`;
  }
  function tileClass(f) {
    if (state.lens === 'build') {
      const cls = CODE_CLS[String(f.code_status || '').toUpperCase()] || 'fm-neutral';
      return f.code_status ? cls + ' fm-hatched' : cls;
    }
    return 'fm-neutral';
  }
  function epicDot(e) {
    const cls = CODE_CLS[String(e.code_status || '').toUpperCase()] || 'fm-neutral';
    return `<span class="fm-dot ${cls}" title="code: ${escHtml(e.code_status || '—')}${epiTitle(e, 'code_status')}"></span>`;
  }

  function renderMap() {
    const epics = state.idx.epics.filter(e => e.pps_id === state.productId);
    const feats = state.idx.features.filter(f => f.pps_id === state.productId);
    if (!epics.length) return `<div class="ph-card"><p class="muted">No epics indexed for this product yet.</p></div>`;
    return `<div class="fm-grid">${epics.map(e => {
      const tiles = feats.filter(f => f.epic === e.id);
      return `<div class="fm-epic" data-node="${escHtml(e.id)}">
        <button class="fm-epic-head" data-sel="${escHtml(e.id)}" title="${escHtml(e.title || e.id)}">
          ${epicDot(e)}<span class="fm-epic-id">${escHtml(e.id)}</span>
          <span class="fm-epic-title">${escHtml(shortTitle(e.title))}</span>
          ${renderMix(e.id)}
          ${renderPins(e.id)}
        </button>
        <div class="fm-tiles">${tiles.map(f =>
          `<button class="fm-tile ${tileClass(f)}" data-node="${escHtml(f.id)}" data-sel="${escHtml(f.id)}"
             title="${escHtml(f.id)} ${escHtml(f.title || '')} · code: ${escHtml(f.code_status || '—')}${epiTitle(f, 'code_status')}">
             <span class="fm-tile-id">${escHtml(f.id)}</span>
             <span class="fm-tile-t">${escHtml(shortTitle(f.title))}</span>
             ${state.lens === 'readiness' ? rCells(f, e) : ''}
             ${renderPins(f.id)}
          </button>`).join('') || '<span class="fm-empty">no features indexed</span>'}</div>
      </div>`;
    }).join('')}</div>`;
  }

  function ghBlob(path) {
    const u = (typeof CONFIG !== 'undefined' && CONFIG.username) || 'venkateshcs-ux';
    return `https://github.com/${u}/V-Pro-Hub/blob/master/${path}`;
  }

  function renderPanel() {
    if (!state.sel) return `<div class="fm-panel fm-panel-hint">Click an epic header or feature tile to drill in — cards, scenarios and evidence documents for that node appear here.</div>`;
    const id = state.sel;
    const isEpic = id.startsWith('E-');
    const node = (isEpic ? state.idx.epics : state.idx.features).find(n => n.id === id) || {};
    const homed = state.idx.cards.filter(c => (c.feature || c.epic) === id || (isEpic && c.epic === id));
    const touching = state.idx.cards.filter(c => (c.touches || []).includes(id));
    const homedIds = new Set(homed.map(c => c.id));
    const docs = state.idx.docs.filter(d => d.card && homedIds.has(String(d.card)));
    const dims = [
      ['code', node.code_status, 'code_status'], ['testing', node.testing_status, 'testing_status'],
      ['manual', node.usermanual_status, 'usermanual_status'],
    ].filter(x => x[1]);
    return `<div class="fm-panel">
      <div class="fm-panel-h">
        <a href="#/${isEpic ? 'epic' : 'feature'}/${escHtml(id)}" class="fm-panel-id">${escHtml(id)}</a>
        <span class="fm-panel-title">${escHtml(node.title || '')}</span>
      </div>
      ${dims.length ? `<div class="fm-panel-dims">${dims.map(([k, v, fld]) => {
        const ep = window.HealthCore.epistemic(node, fld);
        const hatch = ep.state === 'unverified' ? ' fm-hatched' : '';
        return `<span class="fm-dim${hatch}" title="${escHtml(window.HealthCore.hatchTitle(ep))}">${k}: <b class="${CODE_CLS[String(v).toUpperCase()] || ''}">${escHtml(v)}</b>${ep.state === 'unverified' ? `<i class="fm-since">≤${escHtml(ep.since || '?')}</i>` : ''}</span>`;
      }).join('')}</div>` : ''}
      <div class="fm-panel-sec">CARDS HOMED HERE (${homed.length})</div>
      ${homed.length ? homed.map(c => `<a class="fm-row" href="#/card/${escHtml(c.id)}">
          <span class="fm-pin ${WT_CLS[c.work_type] || 'fm-wt-feat'}">#${escHtml(c.id)}</span>
          <span class="fm-row-t">${escHtml(c.title || '')}</span>
          <span class="fm-row-s">${escHtml(c.status || '')}${c.todos_blocked ? ' · ' + c.todos_blocked + ' blocked' : ''}</span>
        </a>`).join('') : '<div class="fm-none">none</div>'}
      <div class="fm-panel-sec">TOUCHED BY (${touching.length})</div>
      ${touching.length ? touching.map(c => `<a class="fm-row" href="#/card/${escHtml(c.id)}">
          <span class="fm-pin ${WT_CLS[c.work_type] || 'fm-wt-feat'}">#${escHtml(c.id)}</span>
          <span class="fm-row-t">${escHtml(c.title || '')}</span>
        </a>`).join('') : '<div class="fm-none">none</div>'}
      <div class="fm-panel-sec">EVIDENCE DOCS (${docs.length})</div>
      ${docs.length ? docs.map(d => `<a class="fm-row" href="${ghBlob(d.path)}" target="_blank" rel="noopener">
          <span class="fm-doc-ic">▤</span><span class="fm-row-t">${escHtml(d.path.split('/').pop())}</span>
          <span class="fm-row-s">${escHtml(d.doc_type || '')}</span>
        </a>`).join('') : '<div class="fm-none">none linked via card frontmatter</div>'}
    </div>`;
  }

  // #211 phase-0 §3-promotion — the honest headline: how much of this map can
  // currently be verified. Computed from the integrity block + SENSED flags;
  // enriches with the manifest half in phase 1.
  function renderHeadline() {
    const ig = state.idx.integrity;
    if (!ig) return '';
    const stamp = window.HealthCore.latestStamp(state.idx.epics.filter(e => e.pps_id === state.productId), 'code_status');
    const parts = [`${ig.nodes} nodes indexed`];
    if (ig.violations) parts.push(`${ig.violations} integrity violations portfolio-wide (${ig.homeless_cards.length} homeless legacy cards)`);
    parts.push(`code/testing/manual are hand-set — not verified since ${stamp || 'unknown'} (hatched)`);
    return `<div class="fm-headline" title="no value is rendered as more certain than it is — CP/CC doctrine 2026-07-31">${parts.map(escHtml).join(' · ')}</div>`;
  }

  function renderShell(container) {
    const gen = state.idx.generated_at || '';
    container.querySelector('#fm-host').innerHTML = `
      ${renderHeadline()}
      <div class="fm-bar">
        <div class="fm-lenses">
          <button class="fm-lens ${state.lens === 'build' ? 'active' : ''}" data-lens="build">Build</button>
          <button class="fm-lens ${state.lens === 'readiness' ? 'active' : ''}" data-lens="readiness" title="five segments per feature: spec · code · test · doc · live (#211 phase-1)">Readiness</button>
          <button class="fm-lens ${state.lens === 'flight' ? 'active' : ''}" data-lens="flight">Work in flight</button>
        </div>
        <span class="fm-gen">index generated ${escHtml(gen)}</span>
      </div>
      ${renderStrip()}
      <div class="fm-body">
        <div class="fm-map-col">${renderMap()}</div>
        <div class="fm-panel-col">${renderPanel()}</div>
      </div>`;
    wire(container);
  }

  function wire(container) {
    container.querySelectorAll('.fm-lens').forEach(b => b.addEventListener('click', () => {
      state.lens = b.dataset.lens; renderShell(container);
    }));
    container.querySelectorAll('.fm-strip-chip, .fm-strip-clear').forEach(b => b.addEventListener('click', () => {
      const wt = b.dataset.wt || null;
      state.wtFilter = (state.wtFilter === wt) ? null : wt;
      if (state.wtFilter && state.lens !== 'flight') state.lens = 'flight';  // filtering implies the flight lens
      renderShell(container);
    }));
    container.querySelectorAll('[data-sel]').forEach(el => el.addEventListener('click', (ev) => {
      if (ev.target.closest('.fm-pin')) return;   // pin hover/click ≠ node select
      state.sel = el.dataset.sel; renderShell(container);
    }));
    // touches[] cross-highlight (hover a pin → touched nodes glow)
    container.querySelectorAll('.fm-pin[data-touches]').forEach(pin => {
      const ids = (pin.dataset.touches || '').split(',').filter(Boolean);
      pin.addEventListener('mouseenter', () => ids.forEach(id => {
        const n = container.querySelector(`[data-node="${id}"]`); if (n) n.classList.add('fm-glow');
      }));
      pin.addEventListener('mouseleave', () => container.querySelectorAll('.fm-glow').forEach(n => n.classList.remove('fm-glow')));
    });
  }

  async function render(container, productId, opts) {
    opts = opts || {};
    state.productId = productId;
    container.innerHTML = `<div id="fm-host"><p class="muted">Loading index…</p></div>`;
    try {
      const raw = await Repos.getFile(opts.owner || CONFIG.username, opts.repo || 'V-Pro-Hub', 'docs/INDEX.json', opts.branch);
      state.idx = JSON.parse(raw);
    } catch (e) {
      container.querySelector('#fm-host').innerHTML = `<div class="ph-card"><p class="muted">INDEX.json unavailable (${escHtml(e.message)}). Run scripts/generate_index.py.</p></div>`;
      return;
    }
    renderShell(container);
  }

  return { render };
})();
